

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xio1020
      MYSQL_DATABASE: CatShopDB
      MYSQL_USER: xio
      MYSQL_PASSWORD: xio1020
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
